"""
Risk reference data management.

This module provides lazy-loading and caching for the risk reference table
to optimize memory usage and startup time.
"""

import pandas as pd
from functools import lru_cache


@lru_cache(maxsize=1)
def get_risk_reference_table() -> pd.DataFrame:
    """Load risk reference table lazily and cache it in memory.

    This file is generated by running the function generate_reference_table_risk().
    Loading lazily reduces startup time and memory usage.

    The function uses @lru_cache to ensure the data is loaded only once per
    Python process and reused across all subsequent calls. This is safe for
    Cloud Run as each container instance has its own cache.

    Returns
    -------
    pd.DataFrame
        Risk reference table with multi-index (tdb, rh, tg, wind_speed, sport_id)

    Notes
    -----
    - The cache is per-process (safe for Cloud Run multi-instance deployment)
    - Memory usage: ~50-200 MB depending on the table size
    - The data is loaded on first call, not at module import time
    """
    return pd.read_parquet("assets/risk_reference_table.parquet")

